# Exercise dependency selection without fetching repositories or building CUDA.
if(NOT DEFINED GREEN_TEST_BINARY_DIR)
    message(FATAL_ERROR "A dedicated build directory must be specified")
endif()
set(mock_dir "${GREEN_TEST_BINARY_DIR}/thc-cmake-test-modules")
file(MAKE_DIRECTORY "${mock_dir}")
file(WRITE "${mock_dir}/FetchContent.cmake" [=[
function(FetchContent_Declare name)
    cmake_parse_arguments(FETCH "" "GIT_REPOSITORY;GIT_TAG" "" ${ARGN})
    set_property(GLOBAL PROPERTY "test_${name}_repo" "${FETCH_GIT_REPOSITORY}")
    set_property(GLOBAL PROPERTY "test_${name}_tag" "${FETCH_GIT_TAG}")
endfunction()
function(FetchContent_MakeAvailable name)
endfunction()
]=])
list(PREPEND CMAKE_MODULE_PATH "${mock_dir}")
include("${GREEN_SOURCE_DIR}/cmake/AddGreenKernel.cmake")
set(GREEN_RELEASE "v1.0.0")
foreach(gpu_url IN ITEMS
        "https://github.com/Green-Phys/green-gpu"
        "https://github.com/Green-Phys/green-gpu.git"
        "https://github.com/Chenan-Phys/green-gpu.git")
    add_green_kernel("${gpu_url};https://example.test/custom-kernel")
    get_property(repo GLOBAL PROPERTY test_green-gpu_repo)
    get_property(tag GLOBAL PROPERTY test_green-gpu_tag)
    if(NOT tag STREQUAL GREEN_GPU_REVISION)
        message(FATAL_ERROR "GPU URL did not select the coordinated revision: ${gpu_url}")
    endif()
    if(NOT repo STREQUAL "https://github.com/Chenan-Phys/green-gpu.git")
        message(FATAL_ERROR "GPU URL did not select the feature repository: ${repo}")
    endif()
    get_property(other_tag GLOBAL PROPERTY test_custom-kernel_tag)
    if(NOT other_tag STREQUAL "v1.0.0")
        message(FATAL_ERROR "Unrelated kernel baseline changed")
    endif()
endforeach()
